- name: Ping all hosts
  hosts: all
  tasks:
  - name: Check connectivity
    ping:
    register: ping_result
  - name: Debug the ping result
    debug:
      msg: "debug says: {{ ping_result }}"
  - name: Get all facts
    debug:
      var: ansible_facts
  - name: Print IP Address
    debug: 
      msg: >   
        this host uses IP address 
        {{ ansible_facts.default_ipv4.address }}
